Repository facebook/facebook-for-woocommerce, pull requests merged in 2021-06, with the labels that each got.

#1982 Add placeholder replace paths.
  package.json
Labels: type: enhancement

#1972 Add tracker props to understand usage of feed-based sync and other FB business config options
  class-wc-facebookcommerce.php
  facebook-commerce.php
  includes/API/FBE/Configuration/Read/Response.php
  includes/Feed/FeedConfigurationDetection.php
  includes/Handlers/Connection.php
  includes/Products/Feed.php
  includes/Utilities/Tracker.php
  includes/fbgraph.php
  includes/fbproductfeed.php
Labels: GH Review: review-needed, status: blocked, type: documentation

#1933 Create a single class responsible for validating whether a product should be synced to FB
  class-wc-facebookcommerce.php
  facebook-commerce.php
  includes/AJAX.php
  includes/ProductSync/ProductExcludedException.php
  includes/ProductSync/ProductValidator.php
  includes/Products.php
Labels: feature: product sync

#1924 Improved product sync feed generation engine with enhanced performance on large stores
  bin/GenerateCategories.php
  class-wc-facebookcommerce.php
  composer.json
  composer.lock
  facebook-commerce.php
  includes/Feed/FeedApiEndpoint.php
  includes/Feed/FeedDataExporter.php
  includes/Feed/FeedFileHandler.php
  includes/Feed/FeedProductFormatter.php
  includes/Feed/FeedScheduler.php
  includes/Jobs/AbstractChainedJob.php
  includes/Jobs/GenerateProductFeed.php
  includes/Jobs/JobRegistry.php
  includes/Lifecycle.php
  includes/Products/FBCategories.php
  includes/Products/Feed.php
  includes/Products/Sync.php
  includes/fbproduct.php
  includes/fbproductfeed.php
  includes/test/facebook-integration-test.php
  includes/test/fbproductfeed-test.php
Labels: GH Review: review-needed, feature: product sync, type: enhancement

#1995 add a <details> element to issue template so logs/status report are nested
  .github/ISSUE_TEMPLATE/1-Bug-report.md
Labels: type: task

#1994 don't delete cached tracker info transients when generating tracker snapshot
  includes/Utilities/Tracker.php
Labels: GH Review: review-needed

#1998 Rename ig to instagram in tracker for better selfdocumentation.
  includes/Utilities/Tracker.php
Labels: type: documentation

#1986 Set empty `sale_price` for products that aren't on sale
  includes/Feed/FeedProductFormatter.php
  includes/fbproduct.php
Labels: GH Review: review-needed, status: blocked

#1999 Add validation to product feed file generation.
  includes/Jobs/GenerateProductFeed.php
Labels: GH Review: review-needed

#2002 Add/filter to change batch size
  includes/Jobs/GenerateProductFeed.php
Labels: GH Review: review-needed, memory enhancement, type: enhancement

#2011 Fix visibility parameter value for items if not visible.
  facebook-commerce.php
  includes/Products.php
  includes/fbproduct.php
  tests/integration/Products/Sync/BackgroundTest.php
  tests/integration/WC_Facebook_Product_Test.php
Labels: GH Review: review-needed, feature: product sync

#2004 Add feed overview link.
  includes/Admin/Settings_Screens/Connection.php
Labels: GH Review: review-needed, feature: product sync

#2019 Fix #2018 - Correct Content IDs in Purchase event
  facebook-commerce-events-tracker.php
Labels: GH Review: review-needed, feature: pixel events & conversion tracking

#2033 Add hook to allow disable of full batch api sync (e.g. for large stores) to avoid potential performance issues
  changelog.txt
  facebook-commerce.php
  includes/AJAX.php
  includes/Admin/Settings_Screens/Product_Sync.php
  includes/Handlers/Connection.php
  readme.txt
Labels: GH Review: review-needed, feature: onboarding, feature: product sync
