Repository facebook/facebook-for-woocommerce, pull requests merged in 2021-05, with the labels that each got.

#1923 Fix/comments errors phpcs
  facebook-commerce-messenger-chat.php
  facebook-commerce-pixel-event.php
  facebook-commerce.php
  facebook-for-woocommerce.php
Labels: type: enhancement

#1919 Use PSR-4 composer autoloader rather than requiring all classes upfront
  class-wc-facebookcommerce.php
  composer.json
  sake.config.js
Labels: memory enhancement

#1926 add readme.md with essential dev/support info and links
  README.md
Labels: GH Review: review-needed, type: documentation, type: task

#1930 link out to ideas board in feedback/idea issue template + fix bug template heading
  .github/ISSUE_TEMPLATE/1-Bug-report.md
  .github/ISSUE_TEMPLATE/3-Feedback-idea.md
Labels: GH Review: review-needed, type: documentation

#1932 add option for disabling existing feed
  facebook-commerce.php
  includes/Products/Feed.php
Labels: type: documentation, type: enhancement

#1938 Reorder and document feed fields
  includes/Products/class-fb-feed-generator.php
Labels: GH Review: review-needed, needs feedback, needs investigation

#1947 Use Woorelease for deployments
  .gitignore
  bin/build-zip.sh
  changelog.txt
  class-wc-facebookcommerce.php
  facebook-for-woocommerce.php
  package-lock.json
  package.json
  readme.txt
Labels: type: enhancement

#1962 Clean up background sync options
  includes/Jobs/CleanupSkyvergeFrameworkJobOptions.php
  includes/Jobs/JobRegistry.php
  includes/Utilities/Heartbeat.php
Labels: GH Review: review-needed, feature: product sync

#1959 Release PR: Facebook for WooCommerce 2.5.0
  changelog.txt
  facebook-for-woocommerce.php
  package-lock.json
  package.json
  readme.txt
Labels: type: task

#1980 Fix `fb_reset_product is not defined` errors by adding relevant JS functions to `window`
  assets/js/admin/infobanner.js
  assets/js/admin/metabox.js
Labels: GH Review: review-needed

#1985 regenerate package-lock.json to update indirect dependencies
  package-lock.json
  package.json
Labels: GH Review: review-needed, type: task
