Repository facebook/facebook-for-woocommerce, pull requests merged in 2021-03, with the labels that each got.

#1787 Facebook version bump marketing api to 9.0
  includes/API.php
  includes/Admin/Settings_Screens/Advertise.php
  includes/Handlers/Connection.php
  includes/ProductSets/Sync.php
  includes/fbgraph.php
  tests/integration/APITest.php
Labels: CLA Signed

#1794 Sanitize attribute names to correctly auto-match EC attributes
  includes/Products.php
  includes/fbproduct.php
  includes/fbutils.php
Labels: CLA Signed

#1795 Fixes / optimizations for enhanced catalog attribute syncing
  includes/Products.php
  includes/fbproduct.php
  includes/fbutils.php
Labels: CLA Signed

#1791 Don’t autoload OPTION_GOOGLE_PRODUCT_CATEGORIES
  includes/Admin/Google_Product_Category_Field.php
Labels: CLA Signed

#1793 Remove legacy catalog sync API calls
  facebook-commerce.php
  includes/API.php
  includes/Admin.php
  includes/Admin/Settings_Screens/Commerce.php
  includes/Commerce/Orders.php
  includes/Products.php
  includes/fbgraph.php
  tests/integration/APITest.php
  tests/integration/Products_Test.php
  tests/integration/WC_Facebookcommerce_Integration_Test.php
Labels: CLA Signed

#1783 FIX for: Logs being recorded even with debug option disabled
  class-wc-facebookcommerce.php
Labels: CLA Signed

#1808 Create 2.3.3. upgrade function.
  includes/Lifecycle.php
Labels: CLA Signed, GH Review: needs-revision

#1827 Add missing static scope for get_variant_option_name
  includes/fbutils.php
Labels: GH Review: review-needed

#1802 Register WooCommerce Navigation items (updated)
  includes/Admin/Settings.php
Labels: CLA Signed, compatibility, type: enhancement

#1797 Release 2.3.3
  changelog.txt
  class-wc-facebookcommerce.php
  facebook-for-woocommerce.php
  i18n/languages/facebook-for-woocommerce.pot
  includes/Admin/Google_Product_Category_Field.php
  includes/Lifecycle.php
  includes/Products.php
  includes/fbproduct.php
  includes/fbutils.php
  readme.txt
Labels: CLA Signed

#1830 Add default image placeholder for products without image.
  assets/images/woocommerce-placeholder.png
  includes/fbproduct.php
Labels: GH Review: review-needed

#1828 Regenerate indexes after filtering.
  includes/fbproduct.php
Labels: GH Review: review-needed

#1844 Temporarily disable sync on update
  includes/Lifecycle.php
Labels: GH Review: review-needed

#1817 add connection state (boolean) to tracker snapshot
  class-wc-facebookcommerce.php
  includes/Utilities/Tracker.php
Labels: CLA Signed
