Repository facebook/facebook-for-woocommerce, pull requests merged in 2021-04, with the labels that each got.

#1840 Optimise memory usage for whole catalog sync scenario.
  changelog.txt
  includes/Products/Sync.php
  includes/fbproductfeed.php
  includes/fbutils.php
Labels: GH Review: review-needed

#1810 Fix/refactor google product categor datasource
  bin/GenerateCategories.php
  bin/taxonomy-with-ids.en-US.txt
  includes/Admin/Google_Product_Category_Field.php
  includes/Admin/Product_Categories.php
  includes/Admin/Products.php
  includes/Lifecycle.php
  includes/Products/FBCategories.php
  includes/Products/GoogleProductTaxonomy.php
  includes/Products/fb_google_product_categories_en_US_simple.json
  sake.config.js
Labels: CLA Signed, GH Review: review-needed

#1820 Check parent category for attributes if current category has none.
  changelog.txt
  includes/Products/FBCategories.php
Labels: CLA Signed, GH Review: review-needed

#1855 Use sentence caps instead of title caps for `Product sets` nav item
  includes/Admin/Settings_Screens/Product_Sets.php
Labels: GH Review: review-needed, needs feedback

#1860 Rename Uninstall to Disconnect and always clear options.
  changelog.txt
  includes/Admin/Settings_Screens/Connection.php
  includes/Handlers/Connection.php
Labels: GH Review: review-needed

#1866 Update connect/disconnect notes text.
  includes/Handlers/Connection.php
Labels: feature: onboarding

#1845 add query monitor profiling to three specific product-sync code paths
  includes/Products/Sync.php
  includes/Products/Sync/Background.php
  includes/fbproductfeed.php
Labels: status: blocked

#1865 Add tracker props for key features: product sync, messenger
  includes/Utilities/Tracker.php
Labels: GDPR, GH Review: review-needed

#1872 Fix broken modal JS error when changing product sync or other settings
  includes/Admin.php
Labels: GH Review: review-needed, feature: product sync

#1885 use existing / current tab for connection flow `Get Started` button
  includes/Admin/Settings_Screens/Connection.php
Labels: GH Review: review-needed, feature: onboarding

#1888 Update `Coding Style` section and add `PULL_REQUEST_TEMPLATE.md`
  .github/CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: GH Review: needs-revision, needs feedback

#1857 Handle and log connection errors
  class-wc-facebookcommerce.php
  includes/Exceptions/ConnectWCAPIException.php
  includes/Handlers/Connection.php
Labels: GH Review: needs-revision, needs feedback

#1914 Release 2.4.1 patch version.
  assets/js/admin/facebook-for-woocommerce-products-admin.min.js
  assets/js/admin/facebook-for-woocommerce-products-admin.min.js.map
  bin/GenerateCategories.php
  changelog.txt
  class-wc-facebookcommerce.php
  facebook-for-woocommerce.php
  i18n/languages/facebook-for-woocommerce.pot
  includes/Products/GoogleProductTaxonomy.php
  readme.txt
Labels: status: pending release
