Repository facebook/facebook-for-woocommerce, pull requests merged in 2021-11, with the labels that each got.

#2107 Add compatibility with the WooCommerce checkout block.
  facebook-commerce-events-tracker.php
Labels: GH Review: needs-revision, compatibility, type: bug

#2104 Track batched feed generation time.
  includes/Jobs/GenerateProductFeed.php
  includes/Utilities/Tracker.php
Labels: GH Review: needs-revision

#2118 Fix typo in message retrival.
  facebook-commerce.php
Labels: GH Review: review-needed

#2106 Check for keys before trying to access them.
  includes/Feed/FeedConfigurationDetection.php
Labels: GH Review: review-needed

#1784 Fix empty "value" for variable products
  facebook-commerce-events-tracker.php
Labels: CLA Signed

#2102 Remove feed functions that are no longer used.
  facebook-commerce.php
  includes/Lifecycle.php
  includes/test/facebook-integration-test.php
Labels: GH Review: review-needed, type: enhancement

#2121 Account for parent product description when validating the variation products.
  includes/ProductSync/ProductValidator.php
Labels: GH Review: review-needed, feature: product sync
