Repository facebook/facebook-for-woocommerce, pull requests merged in 2022-08, with the labels that each got.

#2264 Add `release.yml`, update PR template
  .github/PULL_REQUEST_TEMPLATE.md
  .github/release.yml
Labels: changelog: dev

#2267 Release 2.6.20
  .github/PULL_REQUEST_TEMPLATE.md
  .github/release.yml
  changelog.txt
  facebook-commerce.php
  facebook-for-woocommerce.php
  includes/Handlers/Connection.php
  includes/fbproduct.php
  includes/fbutils.php
  package-lock.json
  package.json
  readme.txt
Labels: changelog: none

#2269 Add branch-labels GH workflow
  .github/workflows/branch-labels.yml
Labels: changelog: dev

#2273 Release 2.6.21
  changelog.txt
  facebook-for-woocommerce.php
  package-lock.json
  package.json
  readme.txt
Labels: changelog: none

#2274 Merge branch 'trunk' into develop
  .github/workflows/branch-labels.yml
  changelog.txt
  facebook-for-woocommerce.php
  includes/Events/Event.php
  package-lock.json
  package.json
  readme.txt
Labels: changelog: none

#2252 Changing WooCommerce FBE Flow(Channel) from COMMERCE_OFFSITE to DEFAULT
  includes/Handlers/Connection.php
Labels: feature: onboarding

#2279 Fix - Incorrect content_name and content_ids for variable product when redirect to cart is enabled
  facebook-commerce-events-tracker.php
Labels: type: bug, changelog: fix

#2278 Fix - Out of stock stock products in WooCommerce remain listed on Facebook
  facebook-commerce.php
  includes/Products/Sync.php
Labels: type: bug, changelog: fix

#2280 Fix - Adding an excluded category doesn't remove that category synced products
  facebook-commerce.php
  includes/Products.php
Labels: type: bug, changelog: fix
