Repository facebook/facebook-for-woocommerce, pull requests merged in 2022-11, with the labels that each got.

#2354 Fix - Ensure the enhanced product enhance catalog attributes value is unslashed before saving in the post_meta table
  includes/Products.php
Labels: type: bug, changelog: fix

#2356 Redirect the users to advertise tab of the plugin when FBE is installed
  class-wc-facebookcommerce.php
  includes/Handlers/Connection.php
Labels: feature: onboarding, changelog: update

#2349 Fix duplicate InitiateCheckout when using checkout block.
  facebook-commerce-events-tracker.php
Labels: type: bug, changelog: fix

#2355 Fix - Sync product set when the term name changes.
  includes/ProductSets/Sync.php
Labels: type: bug, changelog: fix

#2365 Release/2.6.30
  changelog.txt
  facebook-for-woocommerce.php
  includes/ProductSets/Sync.php
  package-lock.json
  package.json
  readme.txt
Labels: changelog: none

#2375 Fix - Facebook Product ID is different from what Facebook ID actually is
  includes/Admin/Product_Sync_Meta_Box.php
Labels: type: bug, changelog: fix

#2376 Update API version set in the fbAsyncInit script in Advertise tab.
  includes/Admin/Settings_Screens/Advertise.php
Labels: changelog: tweak

#2368 Debug tools to help reset settings, delete background options and delete catalog products.
  class-wc-facebookcommerce.php
  facebook-commerce.php
  includes/Handlers/Connection.php
  includes/Jobs/DeleteProductsFromFBCatalog.php
  includes/Jobs/JobManager.php
  includes/Jobs/ResetAllProductsFBSettings.php
  includes/Utilities/DebugTools.php
Labels: type: enhancement, changelog: add

#2390 Remove Facebook Orders sync functionality
  assets/js/admin/orders.js
  includes/AJAX.php
  includes/API.php
  includes/API/Orders/Abstract_Request.php
  includes/API/Orders/Acknowledge/Request.php
  includes/API/Orders/Cancel/Request.php
  includes/API/Orders/Fulfillment/Request.php
  includes/API/Orders/Order.php
  includes/API/Orders/Read/Request.php
  includes/API/Orders/Read/Response.php
  includes/API/Orders/Refund/Request.php
  includes/API/Orders/Request.php
  includes/API/Orders/Response.php
  includes/Admin.php
  includes/Commerce.php
  includes/Commerce/Orders.php
  includes/Utilities/Shipment.php
  webpack.config.js
Labels: changelog: tweak

#2394 Prevent disconnection errors when the user ID is missing.
  includes/Handlers/Connection.php
Labels: type: bug, changelog: fix

#2405 Merge release/3.0.5 into trunk
  .nvmrc
  assets/js/admin/orders.js
  changelog.txt
  class-wc-facebookcommerce.php
  facebook-commerce.php
  facebook-for-woocommerce.php
  includes/AJAX.php
  includes/API.php
  includes/API/Orders/Abstract_Request.php
  includes/API/Orders/Acknowledge/Request.php
  includes/API/Orders/Cancel/Request.php
  includes/API/Orders/Fulfillment/Request.php
  includes/API/Orders/Order.php
  includes/API/Orders/Read/Request.php
  includes/API/Orders/Read/Response.php
  includes/API/Orders/Refund/Request.php
  includes/API/Orders/Request.php
  includes/API/Orders/Response.php
  includes/Admin.php
  includes/Admin/Notes/SettingsMoved.php
  includes/Admin/Product_Sync_Meta_Box.php
  includes/Admin/Settings_Screens/Advertise.php
  includes/Commerce.php
  includes/Commerce/Orders.php
  includes/Handlers/Connection.php
  includes/Jobs/DeleteProductsFromFBCatalog.php
  includes/Jobs/JobManager.php
  includes/Jobs/ResetAllProductsFBSettings.php
  includes/Utilities/DebugTools.php
  includes/Utilities/Shipment.php
  package-lock.json
  package.json
  phpcs.xml.dist
  readme.txt
  webpack.config.js
Labels: changelog: none

#2404 Merge release/3.0.5 into develop
  changelog.txt
  facebook-for-woocommerce.php
  includes/Jobs/DeleteProductsFromFBCatalog.php
  includes/Jobs/ResetAllProductsFBSettings.php
  includes/Utilities/DebugTools.php
  package-lock.json
  package.json
  readme.txt
Labels: changelog: none
