Repository facebook/facebook-for-woocommerce, pull requests merged in 2022-09, with the labels that each got.

#2287 Release 2.6.22
  changelog.txt
  facebook-for-woocommerce.php
  package-lock.json
  package.json
  readme.txt
Labels: changelog: none

#2283 Fix - 2171 Cannot disable Facebook Messenger
  includes/Admin/Settings_Screens/Messenger.php
Labels: type: bug, changelog: fix

#2285 Add check to make sure page property exists.
  includes/API/FBE/Installation/Read/Response.php
Labels: type: bug, changelog: fix

#2291 The hearbeat cron shouldn't update messenger config.
  includes/Handlers/Connection.php
Labels: feature: messenger, changelog: fix

#2294 Release/2.6.23
  changelog.txt
  facebook-for-woocommerce.php
  package-lock.json
  package.json
  readme.txt
Labels: changelog: none

#2292 Track purchase event flag in session variable instead post meta table.
  facebook-commerce-events-tracker.php
Labels: type: bug, changelog: fix

#2303 Update build scripts (Sake removal).
  .gitattributes
  .gitignore
  README.md
  bin/build-zip.sh
  composer.json
  i18n/languages/facebook-for-woocommerce.pot
  package-lock.json
  package.json
  sake.config.js
Labels: changelog: update
