Repository facebook/facebook-for-woocommerce, pull requests merged in 2022-10, with the labels that each got.

#2297 Adding new filter to allow customizing a product group's default variation
  facebook-commerce.php
Labels: needs discussion

#2310 release 2.6.25
  changelog.txt
  facebook-commerce.php
  facebook-for-woocommerce.php
  package-lock.json
  package.json
  readme.txt
Labels: changelog: none

#2308 Add wc_facebook_should_sync_product filter.
  includes/ProductSync/ProductValidator.php
Labels: type: enhancement, changelog: add

#2316 Set catagory attribute to taxonomy value rather than product.
  facebook-commerce-events-tracker.php
Labels: type: bug, changelog: fix

#2314 Switch to Jetpack autoloader. (#1996 PR refresh)
  class-wc-facebookcommerce.php
  composer.json
  composer.lock
Labels: type: enhancement, changelog: dev

#2320 Rename JobRegistry to JobManager.
  class-wc-facebookcommerce.php
  includes/Jobs/JobManager.php
  includes/Products/Feed.php
Labels: changelog: dev

#2326 release 2.6.27
  changelog.txt
  facebook-for-woocommerce.php
  package-lock.json
  package.json
  readme.txt
Labels: changelog: none

#2330 defer sending server side api events.
  facebook-commerce-events-tracker.php
Labels: type: bug, changelog: fix

#2331 Fix google-product-category-fields-loads.js loading on every page.
  includes/Admin.php
Labels: type: bug, changelog: fix

#2334 Ensure bundles are not treated as virtual product on product_sync
  facebook-commerce.php
  includes/fbproduct.php
Labels: type: bug, changelog: fix
