Repository facebook/facebook-for-woocommerce, pull requests merged in 2023-11, with the labels that each got.

#2657 Update docs domain name to Woo.com
  .github/CODE_OF_CONDUCT.md
  .github/ISSUE_TEMPLATE/1-Bug-report.md
  .github/ISSUE_TEMPLATE/2-Support-question.md
  .github/ISSUE_TEMPLATE/3-Feedback-idea.md
  .github/workflows/prepare-release.yml
  README.md
  class-wc-facebookcommerce.php
  includes/Utilities/Tracker.php
  package.json
Labels: changelog: update

#2662 Release 3.1.3 - merge trunk into develop
  changelog.txt
  facebook-for-woocommerce.php
  package-lock.json
  package.json
  readme.txt
Labels: changelog: none

#2663 Remove unneeded "After deploy" steps in `prepare-release.yml` file
  .github/workflows/prepare-release.yml
Labels: changelog: dev

#2665 Remove sync not possible modal.
  assets/js/admin/products-admin.js
  includes/AJAX.php
  includes/Admin.php
Labels: changelog: fix

#2666 Remove mentions of shops.
  readme.txt
Labels: changelog: doc

#2668 Release v3.1.5
  changelog.txt
  facebook-for-woocommerce.php
  package-lock.json
  package.json
  readme.txt
Labels: changelog: none
