Repository facebook/facebook-for-woocommerce, pull requests merged in 2023-07, with the labels that each got.

#2571 Deletes the product from facebook once it is switched to draft.
  facebook-commerce.php
Labels: type: bug, changelog: fix

#2574 Release v3.0.27
  changelog.txt
  facebook-commerce.php
  facebook-for-woocommerce.php
  package-lock.json
  package.json
  readme.txt
Labels: changelog: none

#2566 Adds priority to enhanced catalog attributes and display them as per their priority
  includes/Admin/Enhanced_Catalog_Attribute_Fields.php
Labels: type: enhancement, changelog: add

#2575 Fixes Woo categories synced as Google Product category
  includes/fbproduct.php
  tests/Unit/WCFacebookCommerceIntegrationTest.php
Labels: type: bug, changelog: fix

#2578 Release/3.0.28
  changelog.txt
  facebook-for-woocommerce.php
  includes/Admin/Enhanced_Catalog_Attribute_Fields.php
  includes/fbproduct.php
  package-lock.json
  package.json
  readme.txt
  tests/Unit/WCFacebookCommerceIntegrationTest.php
Labels: changelog: none

#2581 Changes backlink label to 'Go to Facebook Product Sets' on Edit Facebook Product Sets page.
  class-wc-facebookcommerce.php
Labels: type: bug, changelog: fix

#2586 Release/3.0.29
  changelog.txt
  class-wc-facebookcommerce.php
  facebook-for-woocommerce.php
  package-lock.json
  package.json
  readme.txt
Labels: changelog: none
