Repository facebook/facebook-for-woocommerce, pull requests merged in 2023-01, with the labels that each got.

#2424 Made Advertise tab be the default when connected
  class-wc-facebookcommerce.php
  includes/Admin/Abstract_Settings_Screen.php
  includes/Admin/Settings.php
Labels: GH Review: review-needed

#2430 Tweak max node version to support the recent v16.
  package-lock.json
  package.json
Labels: changelog: dev, changelog: tweak

#2433 Release 3.0.7 - merging to develop
  changelog.txt
  facebook-for-woocommerce.php
  includes/Admin/Settings.php
  package-lock.json
  package.json
  readme.txt
Labels: changelog: none

#2429 Bump Marketing API version from v13.0 to v14.0
  includes/API.php
  tests/Unit/ApiTest.php
Labels: changelog: tweak

#2444 Merge release branch 3.0.8 into trunk
  changelog.txt
  facebook-for-woocommerce.php
  includes/API.php
  includes/Framework/Api/Base.php
  includes/Framework/Api/Exception.php
  includes/Framework/Api/JSONRequest.php
  includes/Framework/Api/Request.php
  includes/Framework/Api/Response.php
  includes/Products.php
  package-lock.json
  package.json
  readme.txt
  tests/Unit/ApiTest.php
Labels: changelog: none

#2445 Merge trunk into develop after 3.0.8 release
  changelog.txt
  facebook-for-woocommerce.php
  package-lock.json
  package.json
  readme.txt
Labels: changelog: none

#2452 Use transient flag to keep track of order placed.
  facebook-commerce-events-tracker.php
Labels: type: bug, changelog: fix
