Repository facebook/facebook-for-woocommerce, pull requests merged in 2023-02, with the labels that each got.

#2442 Update meta server with new plugin version information.
  class-wc-facebookcommerce.php
  includes/API.php
  includes/API/FBE/Configuration/Update/Request.php
  includes/ExternalVersionUpdate/Update.php
Labels: type: enhancement, changelog: add

#2467 PHP 8.1 deprecated warnings
  includes/Admin/Product_Sets.php
  includes/Framework/Api/JSONResponse.php
Labels: type: bug, changelog: fix

#2469 Remove `mixed` return type, unsupported in PHP 7.2
  includes/Framework/Api/JSONResponse.php
Labels: type: bug, changelog: none

#2471 Release/3.0.10
  changelog.txt
  class-wc-facebookcommerce.php
  composer.json
  composer.lock
  facebook-for-woocommerce.php
  includes/API.php
  includes/API/FBE/Configuration/Update/Request.php
  includes/Admin/Product_Sets.php
  includes/ExternalVersionUpdate/Update.php
  includes/Framework/Api/JSONResponse.php
  package-lock.json
  package.json
  readme.txt
  tests/Unit/ExternalVersionUpdate/UpdateTest.php
Labels: changelog: none

#2473 Fix - New product gets "Do not sync" by default
  includes/Admin.php
Labels: type: bug, changelog: fix

#2476 Product version bump update
  changelog.txt
  facebook-for-woocommerce.php
  package-lock.json
  package.json
  readme.txt
Labels: changelog: none

#2475 Merge 3.0.11 into trunk
  changelog.txt
  facebook-for-woocommerce.php
  includes/Admin.php
  package-lock.json
  package.json
  readme.txt
Labels: changelog: none

#2479 Replace is_ajax calls with wp_doing_ajax()
  includes/Framework/Helper.php
  includes/Framework/Lifecycle.php
  includes/Utilities/DebugTools.php
Labels: type: technical debt

#2481 Fix out of stock products not deleted in FB.
  includes/Products/Stock.php
Labels: type: bug, changelog: fix

#2483 Release 3.0.12
  changelog.txt
  facebook-for-woocommerce.php
  includes/Framework/Helper.php
  includes/Framework/Lifecycle.php
  includes/Products/Stock.php
  includes/Utilities/DebugTools.php
  package-lock.json
  package.json
  readme.txt
Labels: changelog: add, changelog: none

#2484 Merge trunk into develop after 3.0.12 release
  changelog.txt
  facebook-for-woocommerce.php
  package-lock.json
  package.json
  readme.txt
Labels: changelog: none

#2485 Add a check to ensure WC()->session is not null.
  facebook-commerce-events-tracker.php
Labels: type: bug, changelog: fix

#2486 Release 3.0.13 - merge release branch into trunk
  changelog.txt
  facebook-commerce-events-tracker.php
  facebook-for-woocommerce.php
  package-lock.json
  package.json
  readme.txt
Labels: changelog: none
