Repository facebook/facebook-for-woocommerce, pull requests merged in 2023-06, with the labels that each got.

#2551 Remove the prefix from the retailer ID for variation deletion
  includes/Products/Sync/Background.php
Labels: type: bug, changelog: fix

#2552 Release v3.0.24
  changelog.txt
  facebook-for-woocommerce.php
  includes/Products/Sync/Background.php
  package-lock.json
  package.json
  readme.txt
Labels: changelog: none

#2553 Release v3.0.24
  changelog.txt
  facebook-for-woocommerce.php
  package-lock.json
  package.json
  readme.txt
Labels: changelog: none

#2555 Remove wc-enhanced-select to avoid conflict with woo core behaviour.
  assets/js/admin/google-product-category-fields.js
Labels: type: bug, changelog: fix

#2556 Fix for PHP Warning caused by array_filter() call.
  includes/AJAX.php
Labels: type: bug, changelog: fix

#2558 Check if $response_body is empty.
  includes/Events/AAMSettings.php
Labels: type: bug, changelog: fix

#2557 Update comments after latest changes ( 2556 ).
  includes/AJAX.php
Labels: changelog: none, changelog: update

#2560 Product version bump update
  changelog.txt
  facebook-for-woocommerce.php
  package-lock.json
  package.json
  readme.txt
Labels: changelog: none

#2561 Merge release 3.0.25
  assets/js/admin/google-product-category-fields.js
  changelog.txt
  facebook-for-woocommerce.php
  includes/AJAX.php
  includes/Events/AAMSettings.php
  package-lock.json
  package.json
  readme.txt
Labels: changelog: none

#2567 Release/3.0.26
  changelog.txt
  facebook-for-woocommerce.php
  package-lock.json
  package.json
  readme.txt
Labels: changelog: none

#2569 Deletes the product from facebook once it is switched to draft.
  facebook-commerce.php
Labels: type: bug, changelog: fix
