Repository facebook/facebook-for-woocommerce, pull requests merged in 2023-08, with the labels that each got.

#2594 Sets default value for the `category` field.
  includes/Admin/Product_Categories.php
  includes/fbproduct.php
Labels: type: bug, changelog: fix

#2589 Syncs product with name in ALL CAPS and displays warning
  includes/Admin/Product_Sync_Meta_Box.php
  includes/ProductSync/ProductValidator.php
Labels: type: bug, changelog: fix

#2591 Add GH workflows for release PR w/ checklist & auto merge trunk to develop
  .github/workflows/post-release-automerge.yml
  .github/workflows/prepare-release.yml
Labels: changelog: dev

#2596 Release 3.0.30
  .github/workflows/post-release-automerge.yml
  .github/workflows/prepare-release.yml
  changelog.txt
  facebook-for-woocommerce.php
  includes/Admin/Product_Categories.php
  includes/Admin/Product_Sync_Meta_Box.php
  includes/ProductSync/ProductValidator.php
  includes/fbproduct.php
  package-lock.json
  package.json
  readme.txt
Labels: changelog: none

#2601 Return empty config when facebook_config returns a string.
  facebook-commerce-pixel-event.php
Labels: type: bug, changelog: fix

#2597 Adds a filter to Business Manager ID
  includes/Handlers/Connection.php
Labels: type: enhancement, changelog: add

#2603 make get_options a bit more robust.
  facebook-commerce-pixel-event.php
  tests/Unit/FacebookCommercePixelEventTest.php
Labels: type: enhancement, changelog: fix

#2604 Bump Marketing API version to v17.0
  includes/API.php
Labels: changelog: tweak

#2612 Fix WPML product hiding logic
  includes/fbwpml.php
  tests/Unit/WPMLTest.php
Labels: compatibility, changelog: fix

#2618 Changes property access of product id to public.
  includes/fbproduct.php
Labels: type: bug, changelog: fix

#2619 Adds warning if private properties are accessed outside its class.
  class-wc-facebookcommerce.php
  facebook-commerce-messenger-chat.php
  facebook-commerce.php
  includes/Admin.php
  includes/Admin/Enhanced_Catalog_Attribute_Fields.php
  includes/ProductSync/ProductValidator.php
  includes/fbbackground.php
  includes/fbproduct.php
Labels: changelog: tweak
