Repository facebook/facebook-for-woocommerce, pull requests merged in 2024-05, with the labels that each got.

#2728 Release v3.2.0
  .github/workflows/php-cs-on-changes.yml
  .github/workflows/php-unit-tests.yml
  changelog.txt
  class-wc-facebookcommerce.php
  facebook-commerce-messenger-chat.php
  facebook-commerce.php
  facebook-for-woocommerce.php
  includes/API.php
  includes/API/FBE/Configuration/Messenger.php
  includes/API/FBE/Configuration/Read/Response.php
  includes/API/FBE/Configuration/Update/Request.php
  includes/Admin/Settings.php
  includes/Admin/Settings_Screens/Messenger.php
  includes/Admin/Settings_Screens/Product_Sync.php
  includes/Handlers/Connection.php
  includes/Lifecycle.php
  includes/Utilities/Tracker.php
  package-lock.json
  package.json
  readme.txt
  tests/Unit/ApiTest.php
  tests/Unit/WCFacebookCommerceIntegrationTest.php
Labels: changelog: none

#2733 Adds WooCommerce as a dependency to the plugin header
  facebook-for-woocommerce.php
Labels: type: enhancement, changelog: add

#2736 Remove 3.1.13 update step from lifecycle
  includes/Lifecycle.php
Labels: type: bug, changelog: fix

#2737 Revert woo.com → woocommerce.com in URLs
  .github/CODE_OF_CONDUCT.md
  .github/ISSUE_TEMPLATE/1-Bug-report.md
  .github/ISSUE_TEMPLATE/2-Support-question.md
  .github/ISSUE_TEMPLATE/3-Feedback-idea.md
  .github/workflows/prepare-release.yml
  README.md
  class-wc-facebookcommerce.php
  includes/Utilities/Tracker.php
  package.json
Labels: changelog: tweak

#2738 Release/3.2.1
  .github/CODE_OF_CONDUCT.md
  .github/ISSUE_TEMPLATE/1-Bug-report.md
  .github/ISSUE_TEMPLATE/2-Support-question.md
  .github/ISSUE_TEMPLATE/3-Feedback-idea.md
  .github/workflows/prepare-release.yml
  README.md
  changelog.txt
  class-wc-facebookcommerce.php
  facebook-commerce-pixel-event.php
  facebook-for-woocommerce.php
  includes/Lifecycle.php
  includes/Utilities/Tracker.php
  package-lock.json
  package.json
  readme.txt
Labels: changelog: none

#2739 Release/3.2.1 - `trunk` to `develop`
  changelog.txt
  facebook-for-woocommerce.php
  package-lock.json
  package.json
  readme.txt
Labels: changelog: none

#2742 Fix excluded categories in product sets check
  assets/js/admin/product-sets-admin.js
Labels: type: bug, changelog: fix

#2743 Release 3.2.2 - merge release into trunk
  assets/js/admin/product-sets-admin.js
  changelog.txt
  facebook-for-woocommerce.php
  package-lock.json
  package.json
  readme.txt
Labels: changelog: none

#2744 Release 3.2.2 - merge trunk into develop
  changelog.txt
  facebook-for-woocommerce.php
  package-lock.json
  package.json
  readme.txt
Labels: changelog: none

#2640 Adds compat checker for versioning and compatibility
  class-wc-facebookcommerce.php
  composer.json
  composer.lock
  facebook-for-woocommerce.php
Labels: type: enhancement, changelog: add

#2746 Fixes make-pot errors and warnings
  includes/Admin/Settings_Screens/Product_Sync.php
  includes/Framework/Plugin.php
  includes/Framework/Plugin/Dependencies.php
  includes/Framework/Utilities/BackgroundJobHandler.php
  includes/fbutils.php
Labels: type: bug, changelog: fix

#2747 Remove hidden files from build archive
  .gitattributes
Labels: type: bug, changelog: fix

#2751 Update FB GRAPH API version to v20.0
  includes/API.php
Labels: changelog: tweak

#2752 Product version bump update
  changelog.txt
  facebook-for-woocommerce.php
  package-lock.json
  package.json
  readme.txt
Labels: changelog: none

#2753 Release/3.2.3
  .gitattributes
  changelog.txt
  class-wc-facebookcommerce.php
  composer.json
  composer.lock
  facebook-for-woocommerce.php
  includes/API.php
  includes/Admin/Settings_Screens/Product_Sync.php
  includes/Framework/Plugin.php
  includes/Framework/Plugin/Dependencies.php
  includes/Framework/Utilities/BackgroundJobHandler.php
  includes/fbutils.php
  package-lock.json
  package.json
  readme.txt
Labels: changelog: none

#2755 Adds support wp-env
  .gitignore
  .wp-env.json
  package-lock.json
  package.json
Labels: changelog: dev
