Repository facebook/facebook-for-woocommerce, pull requests merged in 2024-08, with the labels that each got.

#2779 fix undefined SETTING_ENABLE_DEBUG_MODE
  includes/Lifecycle.php
Labels: type: bug, changelog: fix

#2786 Release 3.2.7 - merge release into trunk
  .github/workflows/php-cs-on-changes.yml
  changelog.txt
  facebook-for-woocommerce.php
  includes/API/Catalog/Product_Group/Products/Read/Request.php
  includes/API/Catalog/Product_Group/Products/Read/Response.php
  includes/API/Catalog/Product_Item/Find/Request.php
  includes/API/Catalog/Send_Item_Updates/Request.php
  includes/API/FBE/Configuration/Read/Response.php
  includes/API/FBE/Configuration/Update/Request.php
  includes/API/Pixel/Events/Request.php
  includes/API/Request.php
  includes/API/Traits/Idempotent_Request.php
  includes/API/Traits/Rate_Limited_Response.php
  includes/Admin/Enhanced_Catalog_Attribute_Fields.php
  includes/Admin/Notes/SettingsMoved.php
  includes/Admin/Product_Categories.php
  includes/Admin/Product_Sets.php
  includes/Admin/Products.php
  includes/Admin/Settings.php
  includes/ExternalVersionUpdate/Update.php
  includes/Framework/Api/Base.php
  includes/Framework/Api/Response.php
  includes/Framework/Utilities/BackgroundJobHandler.php
  includes/Jobs/CleanupSkyvergeFrameworkJobOptions.php
  includes/Jobs/DeleteProductsFromFBCatalog.php
  includes/Jobs/ResetAllProductsFBSettings.php
  includes/Lifecycle.php
  includes/ProductSync/ProductValidator.php
  includes/Products/Sync/Background.php
  includes/Utilities/DebugTools.php
  includes/fbwpml.php
  package-lock.json
  package.json
  phpcs.xml.dist
  readme.txt
Labels: changelog: none

#2787 Release 3.2.7 - merge trunk into develop
  changelog.txt
  facebook-for-woocommerce.php
  package-lock.json
  package.json
  readme.txt
Labels: changelog: none

#2781 Use get_title() for content_name to match catalog name.
  facebook-commerce-events-tracker.php
Labels: type: bug, changelog: fix

#2788 Redoing how we fetch access tokens from WooCommerce Connect Server.
  includes/Handlers/Connection.php
Labels: changelog: update
