Repository facebook/facebook-for-woocommerce, pull requests merged in 2024-03, with the labels that each got.

#2701 Fix deprecation warnings with PHP 8.2.
  facebook-commerce.php
  includes/Admin/Tasks/Setup.php
  includes/fbproductfeed.php
Labels: priority: high

#2702 Release/3.1.11
  changelog.txt
  facebook-for-woocommerce.php
  package-lock.json
  package.json
  readme.txt
Labels: changelog: none

#2703 Release/3.1.11
  changelog.txt
  facebook-commerce.php
  facebook-for-woocommerce.php
  includes/Admin/Tasks/Setup.php
  includes/fbproduct.php
  includes/fbproductfeed.php
  package-lock.json
  package.json
  readme.txt
Labels: changelog: none

#2697 Updates readme.txt to meet WordPress requirements
  readme.txt
Labels: changelog: update

#2704 Check if condition is set before setting a default value.
  includes/fbutils.php
Labels: type: bug, changelog: fix, changelog: tweak

#2706 Release/3.1.12
  changelog.txt
  facebook-for-woocommerce.php
  includes/fbutils.php
  package-lock.json
  package.json
  readme.txt
Labels: changelog: none

#2707 Release/3.1.12 - `trunk` to `develop`
  changelog.txt
  facebook-for-woocommerce.php
  package-lock.json
  package.json
  readme.txt
Labels: changelog: none

#2708 Add Messenger deprecation warning notices
  assets/css/facebook.css
  facebook-for-woocommerce.php
  includes/Admin/Settings_Screens/Messenger.php
  includes/Lifecycle.php
Labels: type: enhancement, changelog: add

#2714 Remove facebook_messenger_deprecation_warning notice on deactivation.
  facebook-for-woocommerce.php
Labels: type: bug, changelog: fix
